allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@vuepress-plume/plugin-fonts@1.0.0-rc.207'
  - '@vuepress-plume/plugin-search@1.0.0-rc.207'
  - vuepress-plugin-md-power@1.0.0-rc.207
  - vuepress-theme-plume@1.0.0-rc.207
